version: '3'
services:
  api:
    build:
      context: .
      dockerfile: infra/dev/Dockerfile
    ports:
      - '8080:8080'
    working_dir: /opt/app
    env_file:
      - .env
    environment:
      DB_USER: dev
      DB_PASS: dev
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: service-template
    volumes:
      - ./cmd:/opt/app/cmd
      - ./gen:/opt/app/gen
      - ./internal:/opt/app/internal
      - ./go.mod:/opt/app/go.mod
      - ./go.sum:/opt/app/go.sum
